import { Inter } from "next/font/google";
import "./globals.css";
import Wrapper from "@/components/wrapper/Wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "React with Redux Practice Next.js Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
