export const productData = [
    { name: 'Phone', price: 200 },
    { name: 'Laptop', price: 1200 },
    { name: 'Tablet', price: 300 },
    { name: 'Monitor', price: 150 },
    { name: 'Keyboard', price: 50 },
    { name: 'Mouse', price: 25 },
    { name: 'Printer', price: 100 },
    { name: 'Headphones', price: 80 },
    { name: 'Speakers', price: 60 },
    { name: 'Camera', price: 500 },
    { name: 'Smartwatch', price: 250 },
    { name: 'Charger', price: 20 },
    { name: 'Router', price: 70 },
    { name: 'Hard Drive', price: 90 },
    { name: 'USB Cable', price: 10 },
    { name: 'Webcam', price: 40 },
    { name: 'Microphone', price: 35 },
    { name: 'Desk Lamp', price: 45 },
    { name: 'Projector', price: 600 },
    { name: 'Graphics Card', price: 400 },
    { name: 'RAM', price: 150 },
    { name: 'SSD', price: 120 },
    { name: 'Motherboard', price: 200 },
    { name: 'CPU', price: 300 },
    { name: 'Power Supply', price: 110 },
    { name: 'Case', price: 80 },
    { name: 'Fan', price: 15 },
    { name: 'Cooling Pad', price: 30 },
    { name: 'Game Console', price: 500 },
    { name: 'VR Headset', price: 350 }
];
